# Form implementation generated from reading ui file './08_user_login_registration.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(649, 400)
        self.widget = QtWidgets.QWidget(parent=window)
        self.widget.setGeometry(QtCore.QRect(10, 100, 255, 123))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_username = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.text_username.setFont(font)
        self.text_username.setObjectName("text_username")
        self.horizontalLayout_2.addWidget(self.text_username)
        # username输入框
        self.username = QtWidgets.QLineEdit(parent=self.widget)
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.text_password = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.text_password.setFont(font)
        self.text_password.setObjectName("text_password")
        self.horizontalLayout_3.addWidget(self.text_password)

        # password输入框
        self.password = QtWidgets.QLineEdit(parent=self.widget)
        self.password.setObjectName("password")
        self.horizontalLayout_3.addWidget(self.password)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 注册按钮
        self.regist = QtWidgets.QPushButton(parent=self.widget)
        self.regist.setObjectName("regist")
        self.horizontalLayout.addWidget(self.regist)
        # 事件的绑定
        self.regist.clicked.connect(self.click_regist)
        # 登录按钮
        self.login = QtWidgets.QPushButton(parent=self.widget)
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        # 事件的绑定
        self.login.clicked.connect(self.click_login)
        # 重置按钮
        self.reset = QtWidgets.QPushButton(parent=self.widget)
        self.reset.setObjectName("reset")
        # 事件的绑定
        self.reset.clicked.connect(self.click_reset)
        
        self.horizontalLayout.addWidget(self.reset)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_result = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.text_result.setFont(font)
        self.text_result.setObjectName("text_result")
        self.horizontalLayout_4.addWidget(self.text_result)
        self.result = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        # 点击按钮呈现的结果
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.horizontalLayout_4.addWidget(self.result)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def click_regist(self):
        self.result.setText("注册成功")
        self.result.setStyleSheet('color:red')
        
    def click_login(self):
        username = str(self.username.text())
        password = str(self.password.text())
        if (username == 'yuan'):
            if(password == '123456'):
                self.result.setText('登录成功')
                self.result.setStyleSheet('color:red')
            else:
                self.result.setText('密码错误')
                self.result.setStyleSheet('color:black')

        else:
            self.result.setText('账号不存在')
            self.result.setStyleSheet('color:black')
    def click_reset(self):
        self.username.setText('')
        self.password.setText('')
        self.result.setText('重置成功')
        self.result.setStyleSheet('color:black')
        pass



    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "event handing"))
        self.text_username.setText(_translate("window", "username："))
        self.username.setPlaceholderText(_translate("window", "请输入用户名"))
        self.text_password.setText(_translate("window", "password："))
        self.password.setPlaceholderText(_translate("window", "请输入密码"))
        self.regist.setText(_translate("window", "Sign in"))
        self.login.setText(_translate("window", "login"))
        self.reset.setText(_translate("window", "reset"))
        self.text_result.setText(_translate("window", "结果："))
        self.result.setText(_translate("window", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())
